# Generated by Django 5.1.6 on 2025-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebook',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='name',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
    ]
